// Corrected version of fix_missing_caisse_counterpart.js. The first attempt broke the overall
// journal balance because a crude single "plug" entry (id 547, "Régularisation Contrepartie
// Fournisseur (Équilibrage SYSCOHADA)", credit 14 695 185 on compte 401100) was already standing
// in for these same 192 missing caisse counterparts in the aggregate total — it was almost
// certainly generated by the app's own auto-fix-and-import balancing feature during the original
// bulk import, as a shortcut instead of itemizing each règlement's real cash leg.
// This version removes that synthetic placeholder AND adds the 192 real, dated, per-transaction
// caisse counterpart lines (confirmed by the user to be genuine avances versées aux fournisseurs).
const db = require('./db.js');

db.serialize(() => {
  db.get("SELECT COALESCE(MAX(piece_id), 0) as maxId FROM journal", [], (err, row) => {
    if (err) { console.error(err); process.exit(1); }
    let pieceCounter = row.maxId || 0;

    db.all(
      "SELECT id, date, compte_tiers, libelle, n_facture, reference, debit FROM journal WHERE code_journal='CA' AND compte='40100000' AND debit > 0 ORDER BY id",
      [],
      (err2, rows) => {
        if (err2) { console.error(err2); process.exit(1); }
        console.log('Lignes à compléter:', rows.length);

        db.run('BEGIN TRANSACTION');

        db.run("DELETE FROM journal WHERE id = 547", function (delErr) {
          if (delErr) { console.error(delErr); db.run('ROLLBACK'); process.exit(1); }
          console.log('Plug de régularisation supprimé (id 547), lignes affectées:', this.changes);
        });

        const updatePiece = db.prepare('UPDATE journal SET piece_id = ? WHERE id = ?');
        const insertLine = db.prepare(`
          INSERT INTO journal (code_journal, poste_budgetaire, date, compte, compte_tiers, libelle, n_facture, reference, debit, credit, piece_id)
          VALUES ('CA', '', ?, '571100', ?, ?, ?, ?, 0, ?, ?)
        `);

        let total = 0;
        rows.forEach(r => {
          pieceCounter++;
          updatePiece.run(pieceCounter, r.id);
          insertLine.run(
            r.date,
            r.compte_tiers,
            `Mouvement de caisse (avance/règlement fournisseur - contrepartie automatique) - ${r.libelle}`,
            r.n_facture,
            r.reference,
            r.debit,
            pieceCounter
          );
          total += r.debit;
        });

        updatePiece.finalize();
        insertLine.finalize(err3 => {
          if (err3) {
            db.run('ROLLBACK', () => { console.error(err3); process.exit(1); });
            return;
          }
          db.run('COMMIT', err4 => {
            if (err4) { console.error(err4); process.exit(1); }
            console.log('Terminé. Lignes de contrepartie créées:', rows.length, '- Montant total:', total);
            db.get("SELECT SUM(debit) as d, SUM(credit) as c FROM journal", [], (e5, r5) => {
              console.log('APRÈS: debit=', r5.d, 'credit=', r5.c, 'diff=', r5.d - r5.c);
              process.exit(0);
            });
          });
        });
      }
    );
  });
});
